#requires -Version 5.1
param([string]$Control = (Join-Path $PSScriptRoot '..\tools\gad-control.ps1'))
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root=Join-Path ([IO.Path]::GetTempPath()) ('gad-lean02-'+[guid]::NewGuid().ToString('N'))
$repo=Join-Path $root 'repo'; New-Item -ItemType Directory -Path $repo | Out-Null
$results=[ordered]@{}
function G([string[]]$a){$o=@(& git -C $repo @a 2>&1);if($LASTEXITCODE -ne 0){throw($o-join"`n")};($o-join"`n").Trim()}
function Clone($o){(($o|ConvertTo-Json -Depth 30)|ConvertFrom-Json)}
function Check([bool]$ok,[string]$message){if(-not $ok){throw $message}}
function Run($p){$f=Join-Path $root 'package.json';$p|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $f -Encoding UTF8;$raw=& powershell -NoProfile -File $Control -Package $f;($raw|ConvertFrom-Json)}
function Refuse($p,[string]$pattern,[string]$label){$r=Run $p;Check (-not $r.ok -and $r.error -match $pattern) "$label was not refused: $($r.error)"}
try {
 G @('init','-b','main')|Out-Null;G @('config','user.name','Fixture')|Out-Null;G @('config','user.email','fixture@example.invalid')|Out-Null
 'fixture'|Set-Content -LiteralPath (Join-Path $repo 'fixture.txt') -NoNewline;G @('add','.')|Out-Null;G @('commit','-m','fixture')|Out-Null
 $base=[ordered]@{
  repo=$repo;action='governance-check';gate='G3';mainRef='refs/heads/main';target='LEAN-02';batch='LEAN-02'
  classification=[ordered]@{changeClass='C3';risk='R3';governanceProfile='P2';profile='CRITICAL';ambiguous=$false;automaticDowngrade=$false;humanAuthorityRisk=$false;evidenceIntegrityRisk=$true;recoveryRisk=$true;criticalControlFailure=$false;materialRiskUpgrade=$false;stopForGate=$false;expandedAuthorization=$false}
  baseline=[ordered]@{frozen=$true;risks=@('profile-selection','evidence-integrity','failure-classification','coverage-integrity','budget-control','review-independence','scope-control','status-control');requiredTests=@('V1','V2','V3','V4','V5','V6','V7','V8');declaredTests=@('V1','V2','V3','V4','V5','V6','V7','V8');requiredEvidence=@('test-output','coverage-matrix');stopConditions=@('all-required-evidence','review-pass');addedRole=$false;addedCase=$false;budgets=[ordered]@{implementationWorkers='1';reviewerSessions='1';implementationWorktrees='1';mechanicalWorkers='0';reviewRounds='1';reworkRounds='1';dispatchRecords='4';newBranches='1';defaultTotalWorktrees='3';maximumTotalWorktrees='4'}}
  verification=[ordered]@{kinds=@('risk-check','trusted-smoke','affected-integration','coverage','independent-review','independent-gate-audit','failure-recovery');riskChecks=@(@{risk='profile-selection';test='V1'},@{risk='evidence-integrity';test='V2'},@{risk='failure-classification';test='V4'},@{risk='coverage-integrity';test='V5'},@{risk='budget-control';test='V6'},@{risk='review-independence';test='V7'},@{risk='scope-control';test='V8'},@{risk='status-control';test='V8'});trustedSmoke=[ordered]@{cleanFixture=$true;repeatable=$true;exitCode='0';expectedAssertion=$true;skippedRequiredAssertion=$false;retainedInput=$true;retainedOutput=$true;retainedStatus=$true;fixtureId='lean02-clean-fixture';command='powershell -File smoke.ps1';expectedOutput='PASS';retainedEvidenceId='smoke-001'}}
  failure=[ordered]@{classification='product';uncertain=$false;productFailure=$true;expandTests=$false;trustedPathReproduced=$true}
  coverage=@(1..8 | ForEach-Object {@{requirement="R-$($_)";implementation='GovernanceCheck';reachable=$true;evidence="V$($_)";verdict='PASS'}})
  runtime=[ordered]@{implementationWorkers='1';reviewerSessions='1';implementationWorktrees='1';mechanicalWorkers='0';dispatchRecords='2';reviewRounds='1';reworkRounds='0';reviewFailures='0';reReviewReason='NONE';totalWorktrees='3';isolationEvidence=$true;reviewWorktreeFallback=$false;reviewIndependent=$true;reviewIndependenceEvidence=$true;freshReviewerSessionId='review-1';newBranches='1';optionalHardeningInBatch=$false;derivedStatusUpdate=$false;simplify=$false;lowerHumanGate=$false;lowerIndependentReview=$false;lowerEvidence=$false}
 }
 $r=Run $base;Check ($r.ok -and $r.governance.minimumProfile -eq 'CRITICAL') 'V1 valid CRITICAL baseline failed'
 $q=Clone $base;$q.classification.profile='STANDARD';Refuse $q 'below required minimum CRITICAL' 'V1 weaker Profile'
 $q=Clone $base;$q.classification.automaticDowngrade=$true;Refuse $q 'Automatic Profile downgrade' 'V1 automatic downgrade'
 $q=Clone $base;$q.classification.profile='STRICT';$q.classification.ambiguous=$true;Refuse $q 'below required minimum CRITICAL' 'V1 ambiguous Profile';$results.V1='PASS (minimum/ambiguity/downgrade enforced)'
 $q=Clone $base;$q.baseline.frozen=$false;Refuse $q 'must be frozen' 'V2 unfrozen baseline';$q=Clone $base;$q.baseline.declaredTests+=@('V9');Refuse $q 'Unapproved required test' 'V2 added test';$q=Clone $base;$q.baseline.budgets.dispatchRecords='5';Refuse $q 'Frozen budget mismatch' 'V2 changed budget';$results.V2='PASS (risks/tests/evidence/stops/budgets frozen)'
 $q=Clone $base;$q.verification.kinds=@('risk-check');Refuse $q 'Missing CRITICAL verification' 'V3 incomplete mapping';$q=Clone $base;$q.verification.trustedSmoke.retainedOutput=$false;Refuse $q 'Trusted smoke contract' 'V3 untrusted smoke';$results.V3='PASS (Profile minimums and trusted smoke enforced)'
 $q=Clone $base;$q.failure.classification='fixture';$q.failure.productFailure=$false;$q.failure.trustedPathReproduced=$false;$r=Run $q;Check $r.ok 'V4 valid fixture classification failed';$q.failure.productFailure=$true;Refuse $q 'Fixture/harness failure' 'V4 fixture promoted to product failure';$q=Clone $base;$q.failure.uncertain=$true;Refuse $q 'uncertainty requires stop' 'V4 uncertain classification';$results.V4='PASS (fixture/product/uncertain paths separated)'
 $q=Clone $base;$q.coverage[0].reachable=$false;Refuse $q 'REVIEW_FAIL' 'V5 unreachable implementation';$q=Clone $base;$q.coverage[0].evidence='';Refuse $q 'Missing evidence' 'V5 missing evidence';$results.V5='PASS (requirement/implementation/evidence enforced)'
 $q=Clone $base;$q.runtime.dispatchRecords='5';Refuse $q 'resource budget exceeded' 'V6 dispatch overrun';$q=Clone $base;$q.runtime.reviewFailures='2';Refuse $q 'Second review failure' 'V6 second failure';$q=Clone $base;$q.runtime.reReviewReason='UNRELATED_PASS';Refuse $q 'allowed trigger' 'V6 untriggered re-review';$q=Clone $base;$q.runtime.reviewFailures='1';$q.runtime.reworkRounds='1';$q.runtime.reviewRounds='2';$q.runtime.reviewerSessions='2';$q.runtime.reReviewReason='REVIEW_FAIL';$r=Run $q;Check $r.ok 'V6 triggered fresh re-review failed';$results.V6='PASS (Review/Rework/Dispatch budgets enforced)'
 $q=Clone $base;$q.runtime.isolationEvidence=$false;Refuse $q 'Fourth Review Worktree required' 'V7 absent isolation';$q.runtime.reviewWorktreeFallback=$true;$q.runtime.totalWorktrees='4';$r=Run $q;Check $r.ok 'V7 conditional fallback failed';$q=Clone $base;$q.runtime.reviewWorktreeFallback=$true;$q.runtime.totalWorktrees='4';Refuse $q 'conditional, not default' 'V7 default fourth Worktree';$results.V7='PASS (three default; conditional fourth enforced)'
 $q=Clone $base;$q.runtime.optionalHardeningInBatch=$true;Refuse $q 'Optional hardening' 'V8 optional hardening';$q=Clone $base;$q.runtime.derivedStatusUpdate=$true;Refuse $q 'status updates are deferred' 'V8 early status';$q=Clone $base;$q.runtime.simplify=$true;$q.runtime.lowerEvidence=$true;Refuse $q 'Mandatory controls cannot be lowered' 'V8 unsafe SIMPLIFY';$results.V8='PASS (SIMPLIFY/hardening/deferred status enforced)'
 $results|ConvertTo-Json -Compress
} finally {
 if(Test-Path -LiteralPath $root){$resolved=[IO.Path]::GetFullPath($root);if($resolved.StartsWith([IO.Path]::GetFullPath([IO.Path]::GetTempPath()),[StringComparison]::OrdinalIgnoreCase)-and(Split-Path $resolved -Leaf)-like 'gad-lean02-*'){Remove-Item -LiteralPath $resolved -Recurse -Force}}
}
